export JWM_PYTHON="3.10"
export JWM_SERVER_NAME=greatrawr
export JWM_GPU_NUM=1
export JWM_NODES_NUM=1
export JWM_RUN_TIME="1-00:00:00"
export JWM_SLURM_FILE=slurm.sh
export JWM_build_flashattn=
export JWM_NOTEBOOK=
export CUDA_VISIBLE_DEVICES=1
export JWM_TASK_NAMES="ArguAna CQADupstackGamingRetrieval CQADupstackUnixRetrieval ClimateFEVERHardNegatives FEVERHardNegatives FiQA2018 HotpotQAHardNegatives SCIDOCS TRECCOVID Touche2020Retrieval.v3"
export JWM_RUN_COMMAND="python experiments/mteb_eval_layerwise.py   --trained_checkpoint_path ${JWM_DATA_DIR}/output/layerwise/Meta-Llama-3.1-8B-msmarco-mntp-L0/checkpoint-3929   --query_top_k 40   --doc_top_k 400   --output_dir results   --max_length 1024   --task_name ${JWM_TASK_NAMES}"
