PKQ_PYTHON="3.10"
PKQ_SERVER_NAME=berzeliusampere
PKQ_SERVER_NAME=arrhenius
# PKQ_SERVER_NAME=greatrawr
PKQ_GPU_NUM=4
PKQ_NODES_NUM=1
PKQ_RUN_TIME="1-00:00:00"
PKQ_SLURM_FILE=slurm.sh
PKQ_build_flashattn=
PKQ_NOTEBOOK=
PKQ_INTERACTIVE=

MEM_PER_TASK="$((80 * PKQ_GPU_NUM))G"
CPUS_PER_TASK=$((8 * PKQ_GPU_NUM))

CUDA_VISIBLE_DEVICES=1




